server:
  port: 9000
spring:
  application:
    name: index12306-gateway${unique-name:}-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos